### ISSUE TITLE
Short Rest Choose Again

### ISSUE THREAD

**Issue by redguar** [orichalque/yet-an-other-gloomhaven-companion#101]
Unless I am mistaken, your interface does not allow to choose another card upon short sleep, which is a big issue as you need to retap everything and redo the draw manually.

**Comment by orichalque** [comment]
Hi,
I'm not sure I understood your question :/
You can either perform a short rest: that will immediately place a random card from your discard pile to your lost pile, and re-enable the remaining of your discarded cards
Or perform a long rest: a button will appear on your discarded cards, so you can choose the one you want to put to your lost pile.

**Comment by redguar** [comment]
Good day,

 

In the rules, it says : If you do not like the card you drew you can take 1
point of damage to choose another draw.

 

How do we do this with your application ?

**Comment by orichalque** [comment]
Oh, I see what you mean.
That's a really good point: we did not implement this feature yet
@RaphaelPage0110 what do you propose ?

**Comment by orichalque** [comment]
Hi, I just implemented this new feature thanks to your issue.
Once you press the short rest button, a "reroll" button will replace it.
Thus if you do not like your card, you can now reroll it, once, as specified in the rulebook.

Cheers

![image](https://user-images.githubusercontent.com/6909730/81974269-9ec6b380-9625-11ea-94d0-8596ae8d922f.png)
