### ISSUE TITLE
"Triforce" class level 9 card is duplicated

### ISSUE THREAD

**Issue by cboucher-cghy** [orichalque/yet-an-other-gloomhaven-companion#105]
When choosing Triforce class (triple triangle, avoiding spoiler by saying real class name) and showing the level 9 cards, there is a duplicated level 9 card (Ethereal Manifestation) which result in 3 cards level 9 (twice the same).

**Comment by orichalque** [comment]
fixed in ffbfbed
Thanks for opening the issue
