### ISSUE TITLE
Lots of Ability Cards doubled

### ISSUE THREAD

**Issue by redguar** [orichalque/yet-an-other-gloomhaven-companion#106]
I cannot really say which class, but this is the kinda class lots of people have put an X on.

Some cards come back two or three times.

**Comment by orichalque** [comment]
Hi, 
Indeed that is something we noticed. This is an issue that was already present in our database: all summons are duplicated.
We'll try correcting all classes

**Comment by redguar** [comment]
Actually it comes from any2cards.... All summons are there twice in there js/xml.

**Comment by orichalque** [comment]
Exactly, we used his database :)
