### ISSUE TITLE
More obvious graphics for a discarded card (suggestion)

### ISSUE THREAD

**Issue by Provider10** [orichalque/yet-an-other-gloomhaven-companion#107]
Hi there! 

When on the play menu and selecting a card to discard, can it be made more apparent that the card is discarded? Maybe make the surrounding black box bigger or overlaying a transparent symbol over it? If it's something I can adjust in my display I'm happy to do that too

**Comment by orichalque** [comment]
Hi,
This is our current rendering for discarded and lost cards, can you confirm that you have the same one ? (It may differ among browsers ;) )
![image](https://user-images.githubusercontent.com/6909730/88374372-f443dd00-cd99-11ea-82fc-0da6fb698dd7.png)

If you are confortable with CSS, feel free to propose a pull request with graphical changes that seems necessary :)

**Comment by Provider10** [comment]
Done! With a pull request made I think that's the place for any discussion that is to be had, so I will ahead and close this issue
