### ISSUE TITLE
Settings not being saved in cookies

### ISSUE THREAD

**Issue by glenn-fredrx** [orichalque/yet-an-other-gloomhaven-companion#112]
After choosing option to allow cookies, settings are not being saved.

**Comment by orichalque** [comment]
Thanks for opening an issue, we'll check on that :)

**Comment by glenn-fredrx** [comment]
So in looking closer at this, I turned on Developer tools and looked at the cookie information being stored.  I am seeing things like ability cards and gear being stored in the cookies, but it looks like only the gear is being restored when the site is reopened.  I also completely missed the save button at the bottom.
![screenshot cookies](https://user-images.githubusercontent.com/70785189/92308750-ae1b9500-ef65-11ea-81d5-deae246ad54a.png)

**Comment by glenn-fredrx** [comment]
I did some more digging and I see what the issue is.  It loads the ability cards fine, if you have a character from the base "Vanilla" version.  If you have a character from Jaws of the Lion or Frosthaven, it doesn't load that.  I think you need to add a cookie for the version you selected, then load that data.  Then when it loads ability cards it will work fine.

**Comment by glenn-fredrx** [comment]
I think I have a fix for this.  It is working on my local machine.  I don't want to mess up your github repository, as I am really new to this.  So here is the main.js file I modified.  I added the extra cookie for the version of the game and then when loading, use that.
[main.js.txt](https://github.com/orichalque/yet-an-other-gloomhaven-companion/files/5178394/main.js.txt)

**Comment by orichalque** [comment]
This is great, thanks a lot :-) 
I'll merge this as soon as possible !
