### ISSUE TITLE
Add feature to add med pack card from sawbones playable cards

### ISSUE THREAD

**Issue by glenn-fredrx** [orichalque/yet-an-other-gloomhaven-companion#113]
When playing any other class, if the sawbones gives you a med pack card, there is no way to add that to your list of playable cards.

**Comment by orichalque** [comment]
Good point. We'll work on that.

**Comment by RaphaelPage0110** [comment]
Hey @glenn-fredrx , the feature you suggested is now live!
You can activate the exchange card button by going on the menu configuration > Game Options and Enable card exchange.

Let us now what you think of it :)
