### ISSUE TITLE
Add buttons to be blessed/cursed

### ISSUE THREAD

**Issue by RaphaelPageObeo** [orichalque/yet-an-other-gloomhaven-companion#121]
Currently the player has to go to the modifiers tab to add a curse or a blessing, which is pretty cumbersome. We could add two buttons to the Modifiers area on the play are to make this easier.

**Comment by brettmcginnis** [comment]
Created this feature in https://github.com/orichalque/yet-an-other-gloomhaven-companion/pull/122 (we use this app all the time, thank you)
