### ISSUE TITLE
At the end of a round, shuffle the modifiers deck if a *2 or Null modifier was drawn

### ISSUE THREAD

**Issue by RaphaelPage0110** [orichalque/yet-an-other-gloomhaven-companion#126]
Per the rule book : 
![image](https://user-images.githubusercontent.com/26387222/104156971-79738a80-53ea-11eb-910b-e0a8ac7e597e.png)

**Comment by brettmcginnis** [comment]
This pr adds this functionality https://github.com/orichalque/yet-an-other-gloomhaven-companion/pull/129
