### ISSUE TITLE
Elementalist is difficult to tell when using as used and unused cards are almost the same shade of grey

### ISSUE THREAD

**Issue by meisterplaceb** [orichalque/yet-an-other-gloomhaven-companion#135]
When using the abilities section the elementalist is very difficult to play as the grey colors for cards used are the same as the card background

**Comment by orichalque** [comment]
Thanks for opening this issue ! We have the same issue with the sawbone. We'll figure something out, either by changing the play/discard animations for these two classes, or changing the colors of the card with some image processing, we're not sure which one is the best solution yet ...
