### ISSUE TITLE
Ability to reveal and reorder modifier decks

### ISSUE THREAD

**Issue by orphu** [orichalque/yet-an-other-gloomhaven-companion#136]
Perhaps I'm missing it, but is there a way to reveal top X cards and reorder modifier decks? This is required for certain Diviner abilities where you may want to reorder your or another player's deck.

**Comment by orichalque** [comment]
Interesting ! I did not know this ability, we'll think about how to implement that

**Comment by orphu** [comment]
Looks like the main functions would be:

* Reveal top X cards, and reorder them
* Reveal top X cards, send one or more to the bottom of the deck. 

There are more, but they would only apply to the monster deck. Gloomhaven Helper has some nice support for this.

**Comment by orichalque** [comment]
Thanks for the tip, I've never played Diviner ;)

**Comment by orphu** [comment]
Normally, I don't think we would either, but if you want to play the Forgotten Circles scenarios it's required. :/

**Comment by orichalque** [comment]
@orphu We implemented this feature in the v4.7 version of Gloomhaven-deck :)
It is disabled by default, as it is rarely needed ! 
You can check the "sort modifiers" game option, that will add an additional button to the game screen.
There you can display up to 9 modifiers, and reorder them as you want, or putting them at the bottom of your modifier deck.
Thanks for the issue !
