### ISSUE TITLE
JotL Items

### ISSUE THREAD

**Issue by MrHofer** [orichalque/yet-an-other-gloomhaven-companion#147]
When you switch the game options to JotL or FH the items should change to accommodate the game. 

Also, while less important, the JotL characters should really be added to the playable classes for GH.

**Comment by MrHofer** [comment]
Oh also, the level "A" and "B" cards would be handy to add. 

If you're playing with people that have played GH before, playing through the first 4 scenarios without those cards isn't a big deal, but it does throw the game off a bit.

**Comment by orichalque** [comment]
Hi @MrHofer , thanks for your issue :-)
We'll check on that asap !

**Comment by RaphaelPage0110** [comment]
Hi @MrHofer , what did you mean by "Also, while less important, the JotL characters should really be added to the playable classes for GH.". They are available on the app by selecting Game options > Expansions > Jaws of the Lion and going the Abilities tab

**Comment by MrHofer** [comment]
> Hi @MrHofer , what did you mean by "Also, while less important, the JotL characters should really be added to the playable classes for GH.". They are already available on the app by selecting Game options > Expansions > Jaws of the Lion and going the Abilities tab :)

UnIess I'm not seeing something, I don't see "Game Options > Expansions". I see "Game Options > Versions" and there you can select JotL. The issue arises that if you select "Game Options > Versions > Jaws of the Lion," it uses the base Gloomhaven item cards. This is fine if you are using them in GH, but not if you are playing JotL. 

My suggestion would be to add the four JotL characters to the "Locked Classes" section when you have the Version set to "Gloomhaven" so they can be used in Gloomhaven. When you select "Game Options > Versions > Jaws of the Lion" it should change the characters to only the four available for JotL, the items for JotL, and the Battle Goals for JotL exclusively. 

This might not be possible. I have no idea how the coding works, just how the characters work in the game. Thanks for being responsive!

**Comment by RaphaelPage0110** [comment]
> UnIess I'm not seeing something, I don't see "Game Options > Expansions". I see "Game Options > Versions" and there you can select JotL. 

You are correct! I was referencing the 'on development' version (https://gloomhaven-dev.netlify.com/)

>The issue arises that if you select "Game Options > Versions > Jaws of the Lion," it uses the base Gloomhaven item cards. This is fine if you are using them in GH, but not if you are playing JotL.
> 
> My suggestion would be to add the four JotL characters to the "Locked Classes" section when you have the Version set to "Gloomhaven" so they can be used in Gloomhaven. When you select "Game Options > Versions > Jaws of the Lion" it should change the characters to only the four available for JotL, the items for JotL, and the Battle Goals for JotL exclusively.
> 

What we are going to do is to add all the items that can be used in JOTL and change the way the Gear tab works so that only JOTL items will be displayed there if you select the JOTL expansion. We are also going to add the FrostHaven items :)

> This might not be possible. I have no idea how the coding works, just how the characters work in the game. Thanks for being responsive!

No problem at all! Some other changes to the UI will come soon so stay tuned!

**Comment by RaphaelPage0110** [comment]
> 
> 
> Oh also, the level "A" and "B" cards would be handy to add.
> 

What are those? Sorry, we do not own JOTL so the new cards like those are unknow to us.

**Comment by MrHofer** [comment]
> > Oh also, the level "A" and "B" cards would be handy to add.
> 
> What are those? Sorry, we do not own JOTL so the new cards like those are unknow to us.

That makes sense! The first 5 scenarios you play in JotL are introductory scenarios. They have you use simplified cards that you eventually replace with the standards cards. Here is an example of the Red Guard's Card: https://m20336.files.wordpress.com/2020/07/rg_2.png

In the long run these aren't important to have, but I was playing with a new person on Roll20 the other day and it would have been useful to have access to them. They are only used for 3-4 scenarios though, so I'm not sure it's worth it and it doesn't seem like it should be a high priority.

**Comment by RaphaelPage0110** [comment]
> In the long run these aren't important to have, but I was playing with a new person on Roll20 the other day and it would have been useful to have access to them. They are only used for 3-4 scenarios though, so I'm not sure it's worth it and it doesn't seem like it should be a high priority.

I see! If we find these cards, it should be a problem to add them :)
I will open a new issue dedicated to those cards.

**Comment by MrHofer** [comment]
> > UnIess I'm not seeing something, I don't see "Game Options > Expansions". I see "Game Options > Versions" and there you can select JotL.
> 
> You are correct! I was referencing the 'on development' version (https://gloomhaven-dev.netlify.com/)
> 
> > The issue arises that if you select "Game Options > Versions > Jaws of the Lion," it uses the base Gloomhaven item cards. This is fine if you are using them in GH, but not if you are playing JotL.
> > My suggestion would be to add the four JotL characters to the "Locked Classes" section when you have the Version set to "Gloomhaven" so they can be used in Gloomhaven. When you select "Game Options > Versions > Jaws of the Lion" it should change the characters to only the four available for JotL, the items for JotL, and the Battle Goals for JotL exclusively.
> 
> What we are going to do is to add all the items that can be used in JOTL and change the way the Gear tab works so that only JOTL items will be displayed there if you select the JOTL expansion. We are also going to add the FrostHaven items :)


I saw today that the JotL items are in, awesome! One thing, item 14 is in the 1-13 option when you click on them.

**Comment by orichalque** [comment]
Oh, that's my fault. Will change asap ! 
Thanks for the tip :-)
