### ISSUE TITLE
The card chosen by the short rest is not random

### ISSUE THREAD

**Issue by RaphaelPage0110** [orichalque/yet-an-other-gloomhaven-companion#150]
It is always the same card.

**Comment by orichalque** [comment]
Maybe the random should be initialized with a seed

**Comment by orichalque** [comment]
tried 3 times with the exact same scenario and had 3 different cards discarded each time :/ 
how can i reproduce that ?

**Comment by RaphaelPage0110** [comment]
I can't reproduce either. It was either luck or weird glitch. I'm closing this
