### ISSUE TITLE
Abilities listed alphabetically instead of by level.

### ISSUE THREAD

**Issue by MrHofer** [orichalque/yet-an-other-gloomhaven-companion#169]
Abilities are now listed alphabetically instead of by level, was this intentional? It will probably just take some time to adjust, but personally I think this is a significant decrease in ease of use.

**Comment by orichalque** [comment]
Hi, I think that they are ordered by level in the "abilities" view.
In the play view, they are ordered as you added them in your deck :) You can reorder them using drag n drop though 

Are the abilities listed alphabetically in the "abilities" view, or the "play" view ?

**Comment by MrHofer** [comment]
They are ordered by alphabetically in the "Abilities" view. 

It seems to be inconsistent though. It's doing it consistently on this one: https://gloomhaven-dev.netlify.app/#

But it's not consistent on this one: https://www.gloomhaven-deck.com/#

On the non-dev one I had it happen on one computer but not on another, which I guess may be a cookies thing? But the UI layout changing from cookies seems odd.

**Comment by orichalque** [comment]
Wow, indeed, that's very weird ! I'm checking that immediately. Thanks a lot.

**Comment by MrHofer** [comment]
Thank you for working on it!

**Comment by orichalque** [comment]
That's very weird ! 
How to reproduce (on dev):
- Clear your deck
- Pick a class (Tried with Music note and 3 Spears)
- Build any deck 
- Save 
- Refresh (F5)
- Switch to the ability view
KO: Cards are now sorted alphabetically
