### ISSUE TITLE
Save selected Character + Level on Abilities page

### ISSUE THREAD

**Issue by RazYouUp** [orichalque/yet-an-other-gloomhaven-companion#176]
Not sure if this is specific to my browser, but I feel like when I revisit the page for my next scenario it remembers everything except for when I navigate to the Abilities screen and it asks me to either select my class or to select my level. It's not the end of the world, but would be a nice enhancement.

**Comment by orichalque** [comment]
Hi ! Thanks for your feedback.
We save the class chosen in cookies but not the level, that's a good point. 
I'll definitely fix this asap !

**Comment by orichalque** [comment]
> it asks me to either select my class
About this issue, we save the class in cookies so it should be remembered. It not, try clearing your cookies for gloomhaven-deck, and retry :)
Feel free to check if this works for the nightly build version: https://gloomhaven-dev.netlify.app/

**Comment by RazYouUp** [comment]
Thanks for the speedy response! Yes, thinking back it might have been a one-off/old issue, but yeah it's just been the level that's been reset to 1 in more recent times.

**Comment by orichalque** [comment]
It should be merged on dev and master soon :)
