### ISSUE TITLE
Crimson Scales

### ISSUE THREAD

**Issue by MrHofer** [orichalque/yet-an-other-gloomhaven-companion#185]
Any chance that the custom expansion Crimson Scales gets added now that it's officially released?

**Comment by RaphaelPage0110** [comment]
@MrHofer finally found the time to add the expansion :D 
It is only available on the nightly build for now, it should be release soon. Could you try it out and tell me if something is missing?
https://gloomhaven-dev.netlify.com/

**Comment by MrHofer** [comment]
@RaphaelPage0110 You guys are the best!
