### ISSUE TITLE
Duplicate abilities added to hand after limit reached

### ISSUE THREAD

**Issue by RazYouUp** [orichalque/yet-an-other-gloomhaven-companion#186]
Steps to recreate:
1. Select class and level in Abilities page (I'm a level 8 Summoner e.g.)
2. Select your abilities up to your limit (I picked 9 cards) -> Verify you can see those 9 cards on the Play page
3. Select an additional ability past your limit

Expected result: Error to be shown indicating that no more cards can be selected
Actual result: No feedback on Abilities page and the additional ability is added to your hand in the Play page

**Comment by RaphaelPage0110** [comment]
@RazYouUp I added a fix to the dev branch, it should be merged into master soon :)
