### ISSUE TITLE
Add Forgotten Circle expansion

### ISSUE THREAD

**Issue by orichalque** [orichalque/yet-an-other-gloomhaven-companion#188]
https://github.com/any2cards/worldhaven

**Comment by orichalque** [comment]
@RaphaelPage0110 looks like we have included a lot of FC content in our "vanilla" version of GH (e.g., Diviner class).
Shall we separate it ? or leave it as it is ?

**Comment by RaphaelPage0110** [comment]
I would separate them, I think
