### ISSUE TITLE
Center the titles on the Modifiers tab

### ISSUE THREAD

**Issue by RaphaelPageObeo** [orichalque/yet-an-other-gloomhaven-companion#192]
"Special Modifier Deck", "Base Deck" and "Final Modifier Deck" should be centered.

We could also remove the "Modifier Deck" words from them, since we are in the "Modifiers" tab (so we have the info there) and the pile of card underneath can't really be mistaken for something else than a deck.  
What do you think @orichalque ?

**Comment by orichalque** [comment]
not sure about the centered thing. Aligned with the left side seems ok.
atm its like that: 
![image](https://user-images.githubusercontent.com/6909730/147061180-19a3066d-0147-4702-a450-23ce0532c63f.png)
centering it with the column would look like this:
![image](https://user-images.githubusercontent.com/6909730/147061279-cc53b02d-e124-44f8-a026-bf09a290855f.png)
which is weird, dont you think ?

Ok for removing the "modifer" terms though :)

**Comment by RaphaelPageObeo** [comment]
That's weird, on the nightly it looks like this : 
![image](https://user-images.githubusercontent.com/61457677/147061736-beadcedd-ff8e-49d2-8177-95e37e7f5859.png)
With the title not lined up with the cards, which looks ugly.
How about we center both the cards and the titles?

Love the dark mode preview btw

**Comment by orichalque** [comment]
i guess i fixed that while implementing the night mode 8-)

**Comment by orichalque** [comment]
well its on the nightly now, wdyt ?

**Comment by RaphaelPage0110** [comment]
It looks better :)
I'll just fix the titles like we discussed, and I'll close this
