### ISSUE TITLE
Enhancements and Long/Short rest

### ISSUE THREAD

**Issue by RaphaelPage0110** [orichalque/yet-an-other-gloomhaven-companion#195]
![image](https://user-images.githubusercontent.com/26387222/147145224-1bf26049-b63f-4111-b4c8-2ce8a85bacda.png)
On this example, the enhancements are on the Skewer card...which you can not see from what we are displaying on the short and long rest pop-ups.

We should put them on the card...but that doesn't seem feasible. Since it isn't, we should not display the enhancement at all, similarily to the 'Abilities' and 'Enhancement' tab

**Comment by orichalque** [comment]
maybe we could just *not* show the enhancements in these modals ?

**Comment by RaphaelPage0110** [comment]
Yep, that's what I said :D

**Comment by orichalque** [comment]
oops ^^'
