### ISSUE TITLE
Add remove input from filter button

### ISSUE THREAD

**Issue by RaphaelPage0110** [orichalque/yet-an-other-gloomhaven-companion#197]
![image](https://user-images.githubusercontent.com/26387222/147147078-dd355e10-90c6-48d6-86f9-b5b07feba605.png)
A little bit like this button on GMail, it should remove the current input from the filters.

**Comment by orichalque** [comment]
![image](https://user-images.githubusercontent.com/6909730/147218350-cb2e157a-27d5-4f43-844c-056e22f1d856.png)
