### ISSUE TITLE
Ability to Export / Import

### ISSUE THREAD

**Issue by kirk444** [orichalque/yet-an-other-gloomhaven-companion#206]
It seems like the changes are all saved locally in cookies, it would be great to have a method to export (and then import) to move them to a different browser or different device.

**Comment by orichalque** [comment]
Hi ! Thanks for opening this issue :)
That's a good idea, and it shouldnt be very hard to implement. We'll think about that !
Cheers

**Comment by orichalque** [comment]
Added to master :)
