### ISSUE TITLE
Greyscale classes (Saw, Triforce) on Ability Selection screen

### ISSUE THREAD

**Issue by kiwitrav** [orichalque/yet-an-other-gloomhaven-companion#214]
The desaturation of the selected card works on most classes great. Even works OK-ish on Triforce/Elementalist because all of their cards have some color (though trickier)
However many of the Saw/Sawbones cards have no color at all, so when selected there's no visual feedback other than the selected cards list - which isn't as easy to spot which cards are selected when sorting through which cards to give up/take.

No idea on best way to do this - keep zoom on selected cards? Add some sort of flash on the card?

**Comment by orichalque** [comment]
Damn sawbone. We've had some issues with this one already on the play screen, so we changed the UI for something less color-dependant. 
We'll think about that; Or maybe i'll turn the cards white instead ;)
#134 #135

**Comment by kiwitrav** [comment]
Suggestion for keeping readability, perhaps just add a glow to the selected cards?

**Comment by orichalque** [comment]
That would be a simple fix :)

**Comment by orichalque** [comment]
Just applied the same green halo than the play page
![image](https://user-images.githubusercontent.com/6909730/214859511-d7ed7872-7318-4ba3-9567-3c2702a5add3.png)
