### ISSUE TITLE
Ability screen: Always visible number of selected cards?

### ISSUE THREAD

**Issue by kiwitrav** [orichalque/yet-an-other-gloomhaven-companion#218]
Very low priority one this one I think, but maybe having the "Deck X / Y" always visible might be a nice - if low priority - quality of life enhancement?

**Comment by orichalque** [comment]
![image](https://user-images.githubusercontent.com/6909730/155987522-63fe06a2-dc33-43ad-8ef2-84231816481d.png)
You mean this counter? Its always visible I think, isnt it ?

**Comment by kiwitrav** [comment]
![Deck count](https://user-images.githubusercontent.com/37902094/156062155-70214283-bc8d-4630-80c5-4af91d1b93e7.png)
Not on desktop under Chrome or Firefox (probably others too, haven't tried) - In the above I've scrolled down 1 notch and the menu goes off-screen and the deck count starts to go off-screen. I keep scrolling and it will go off screen.

Menu? not a problem - rarely need to access it. 
Deck count has the same behaviour on the Enhancements screen, but you don't need a count of it on that screen.

**Comment by orichalque** [comment]
Ooooh I see ! 
That would indeed improve the UX, good point :)

**Comment by orichalque** [comment]
I qet the header bar to sticky, it stays on top:
![image](https://user-images.githubusercontent.com/6909730/214819626-60f55d74-1a8d-4369-8d25-8396b44cf103.png)

**Comment by kiwitrav** [comment]
Awesome, thank you - nice QoL improvements like this make things much more usable
