### ISSUE TITLE
Envelop X SPOILERS …

### ISSUE THREAD

**Issue by Mjg49** [orichalque/yet-an-other-gloomhaven-companion#223]
Seriously spoilers don’t read farther if you don’t want to know. 
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
Are there plans to add Bladeswarm abilities to the app? Thanks. Mind you the new version Isaac released a few months ago.

**Comment by orichalque** [comment]
Hey, BS is available.
You have to enable the X envelop in the Expansion options:
![image](https://user-images.githubusercontent.com/6909730/159259826-3317c055-9d15-443b-bb81-7deec4dd3567.png)

**Comment by Mjg49** [comment]
I didn’t see the new cards he released in January. . . 

https://cdn.shopify.com/s/files/1/0281/0173/8555/files/Bladeswarm_PnP.pdf

**Comment by Mjg49** [comment]
Is there a way to reopen this?

**Comment by orichalque** [comment]
mb, didnt see there were new cards.

**Comment by Mjg49** [comment]
No worries!! Thanks for keeping this up-to-date! :-)

**Comment by OrigamiFrog1** [comment]
This needs to be re-opened. The character has been redesigned entirely with a new PDF on the website. Any2Cards does have the updated ability cards. Not sure if the Perks were changed.
