### ISSUE TITLE
Add gold, experience, and dungeon objective number tick trackers.

### ISSUE THREAD

**Issue by meisterplaceb** [orichalque/yet-an-other-gloomhaven-companion#224]
I really liked the exp, gold, and health trackers that this helper had...something like this would be awesome but no need for health as the gloomhaven helper app has that built in, but adding a ticker next to the dungeon objectives would be neat

https://asgrabowski.github.io/

**Comment by orichalque** [comment]
Hi, since the gloomhaven helper app can also manage health, exp and gold, we do not plan on adding these to GH-deck :)
