### ISSUE TITLE
Bug: Crimson Scales - Skull - modifier cards

### ISSUE THREAD

**Issue by kiwitrav** [orichalque/yet-an-other-gloomhaven-companion#227]
Hi again!
Just looking to start as a Vermling Spiritcaller and was going through the Modifier deck and noticed the following:
4x (+1) Pierce 2 cards
and
0x (+0) Rolling Pierce 3 cards

There should be:
1x (+1) Pierce 2 cards
and
3x (+0) Rolling Pierce 3 cards

Also checked the nightly - there also.

**Comment by kiwitrav** [comment]
Fix is change "13" to "14" on Lines 936, 941 and 946 of database_cs.js 
https://github.com/orichalque/yet-an-other-gloomhaven-companion/blob/master/js/database_cs.js#L936

**Comment by RaphaelPage0110** [comment]
Hi! It should be fixed on the nightly if you want to check it out @kiwitrav

**Comment by kiwitrav** [comment]
Awesome, that's working great - thank you!

**Comment by orichalque** [comment]
I'm actually working on #226 , once i'm done with it we'll merge and deploy all the changes

**Comment by kiwitrav** [comment]
All good - thank you for this! Seriously deckbuilder makes even in-person games better (let's ignore Saw, lol)
