### ISSUE TITLE
Updated versions of FH starting class ability cards?

### ISSUE THREAD

**Issue by fnv** [orichalque/yet-an-other-gloomhaven-companion#228]
I'd love to keep using gloomhaven-deck for my Frosthaven campaign that's about to start. I see that some of the Frosthaven cards are still in the "old" ability card style. Will those be updated any time soon? It looks like the new style is currently available as part of https://github.com/any2cards/worldhaven so it's hopefully an easy update.

**Comment by orichalque** [comment]
Hi, we haven't been working much on gloomhaven-deck lately, I didnt know these were available, thanks !

If you feel like doing this update I'll be more than happy to accept your pull request though ;)

**Comment by fnv** [comment]
Updated the cards and db and submitted a PR. Cheers!

**Comment by orichalque** [comment]
Thanks a lot :) 
Merged in #229 and #231, and released in v5.6, it is now live.
