### ISSUE TITLE
Monument-reward cards

### ISSUE THREAD

**Issue by kiwitrav** [orichalque/yet-an-other-gloomhaven-companion#238]
Heya, is there a plan to add the monument reward Ability cards in? I see they're added to Any2cards
https://github.com/any2cards/gloomhaven/blob/master/data/milestone-ability-cards.js 
Images: https://github.com/any2cards/gloomhaven/tree/master/images/milestone-ability-cards/trail-of-ashes 

No idea why this is under a ToA folder <shrug>

Adds a typically VERY nice ability card for each character

**Comment by orichalque** [comment]
Hey, I didnt know these, it seems pretty simple to add, I'll do it

**Comment by kiwitrav** [comment]
This is awesome, but is there any chance of hiding the card behind some form of spoiler shield or menu? You're supposed to not know about them until you achieve your "monument" and open the packet.

**Comment by dtmcgregor** [comment]
Hi there, thanks for putting the Milestone cards in. But these should be hidden behind some kind of ‘Unlock Milestone Reward for this class’ option…they’re a class-based quest that unlocks them for the whole class (not just character) after completion for the class in question. They didn’t ship with 1st printing Crimson Scales, but with 2nd printing and the Trail of Ashes expansion.

**Comment by kiwitrav** [comment]
Added #242 to address unlocking milestones
