### ISSUE TITLE
In nightly, Option menu is covered on Abilities screen

### ISSUE THREAD

**Issue by kiwitrav** [orichalque/yet-an-other-gloomhaven-companion#244]
Hi, this may be related to #218 but seeing the following when trying to use Options menu on the nightly:
![image](https://user-images.githubusercontent.com/37902094/215040444-b30d87aa-7bef-4b7d-a0fe-473d0afec3ce.png)

**Comment by kiwitrav** [comment]
Huh... Have refreshed page and am now unable to recreate that - even at various ctrl-zoom levels in the browser.

**Comment by kiwitrav** [comment]
AAH! Recreated:  Only happens on Abilities screen

**Comment by orichalque** [comment]
oh no :(

**Comment by kiwitrav** [comment]
Thanks for the fix :)
