### ISSUE TITLE
Additional Crimson Scales items above #83

### ISSUE THREAD

**Issue by kiwitrav** [orichalque/yet-an-other-gloomhaven-companion#246]
Hi! Is there a chance to get the remaining Crimson Scales items added to the gear? There's the items from 84 to 99 and then there's 16 scenario-reward items - all are already on Any2Cards: https://github.com/any2cards/gloomhaven/tree/master/images/items/crimson-scales 

Thank you!

**Comment by orichalque** [comment]
Hey, sure thing :) Will do this afternoon.

**Comment by kiwitrav** [comment]
Awesome, thank you

**Comment by orichalque** [comment]
You should find the new gear in the nightly, I'll see if I can add more changes before releasing :)

**Comment by orichalque** [comment]
> there's 16 scenario-reward items 

Not finished yet

**Comment by kiwitrav** [comment]
looks good - thanks!
