### ISSUE TITLE
Bug: TUSK Modifiers - 4x heal Tusk 0x heal Owned Summons

### ISSUE THREAD

**Issue by kiwitrav** [orichalque/yet-an-other-gloomhaven-companion#268]
Hi, I see there's 4x of these: https://www.gloomhaven-deck.com/data/attack-modifiers/CF/am-cf-02.jpg 

There should only be two. Instead there should also be two of these:
https://github.com/any2cards/gloomhaven/blob/master/images/attack-modifiers/crimson-scales/CT/cs-am-ct-04.png 

Any chance this could be addressed please? This is the character I've just started. Thank you!!

**Comment by kiwitrav** [comment]
Thank you heaps for the quick turn-around on this one!

**Comment by orichalque** [comment]
Thanks for the issue. Its live on the nightly and shall be live soon.
