### ISSUE TITLE
Click Use on a card placed on the board for one turn

### ISSUE THREAD

**Issue by RaphaelPage0110** [orichalque/yet-an-other-gloomhaven-companion#37]
If you click on the 'use' button of a card placed on the board using the circle arrow symbol (the one signifying that the card should stay on the board only for a turn), a NaN String appears on the card : 

![image](https://user-images.githubusercontent.com/26387222/77857992-1a4cdc80-7201-11ea-8059-12685ea53f1d.png)

I think we should remove the option to 'use' a card in this situation. What do you think @orichalque ?

**Comment by orichalque** [comment]
The use button should not even be there. I'll fix this asap

**Comment by orichalque** [comment]
I fixed this bug, and also left the number visible all time (not only on mouse hover)
78acc12
