### ISSUE TITLE
Add a way to see all previously drawn modifiers 

### ISSUE THREAD

**Issue by RaphaelPage0110** [orichalque/yet-an-other-gloomhaven-companion#38]
It is possible de do so in Gloomhaven Helper and it helps when you have to draw several modifiers in a row (like in the case of an advantage / disadvantage / arrow...)

**Comment by orichalque** [comment]
This looks a lot like #25 , both issues could be solved with the same workaround :)

**Comment by RaphaelPage0110** [comment]
Indeed! I would still like to have a draw animation tho :D

**Comment by orichalque** [comment]
I think something like this is feasible:
https://www.w3schools.com/howto/howto_css_flip_card.asp
