### ISSUE TITLE
Add JOLT and Frosthaven support

### ISSUE THREAD

**Issue by orichalque** [orichalque/yet-an-other-gloomhaven-companion#49]
thanks to any2cards that added support for both
- https://github.com/any2cards/jotl
- https://github.com/any2cards/frosthaven

We could do something like that with radio buttons: (Thanks @RaphaelPage0110 for this amazing drawing)
![radio_gh](https://user-images.githubusercontent.com/6909730/78007435-9567dd00-733e-11ea-8746-778d15ae65c2.png)

**Comment by RaphaelPage0110** [comment]
Added JOTL database with commit 03270cb765c1100b06b8ae47d8737769457b016d

**Comment by RaphaelPage0110** [comment]
JOTL support with perge request #60

**Comment by RaphaelPage0110** [comment]
Added Frosthaven database with commit a1aa3a60cb7085c1533a184f7c4ce4cbd624415b

**Comment by orichalque** [comment]
FH suppose with merge request #67
