### ISSUE TITLE
Small Item Limit Not Adjusted for Cloak of Pockets

### ISSUE THREAD

**Issue by DaGloomKiller** [orichalque/yet-an-other-gloomhaven-companion#57]
The small item limitation should be increased by 2 when player has cloak of pockets equipped.

**Comment by orichalque** [comment]
Thanks for the issue, i'll fix this today.
is there any other items of this kind ?

**Comment by orichalque** [comment]
I reversed the last commit in which I added this.
For now we do not verify if the user is allowed to wear the gear s/he chose.

**Comment by DaGloomKiller** [comment]
Sorry for the slow reply. Thanks for the fix! I haven't run across any other circumstances that adjust the item limit. I like the pop-up reminder that it exceeds item limit, but I'm also for not having a strict limitation. Thanks so much for the great work, this site is awesome!

**Comment by orichalque** [comment]
No worries ;-) 
Thanks for the feedback, glad you like our app :)
