### ISSUE TITLE
Card Enhancements on Ability Cards

### ISSUE THREAD

**Issue by cchatham** [orichalque/yet-an-other-gloomhaven-companion#58]
Maybe I missed how to do it. Is there are way to already to add +1, jumps, blesses, etc to ability cards? We started a game physically before the virus and had upgraded our cards. We love your tool but we can't easily leverage our upgrades.

**Comment by orichalque** [comment]
Hi, glad you like our app.
Card enhancement is not currently implemented, but will be consider it soon.
Stay tuned ;)
