### ISSUE TITLE
Add support for Frosthaven Blink Blade faction

### ISSUE THREAD

**Issue by RaphaelPage0110** [orichalque/yet-an-other-gloomhaven-companion#62]
![image](https://user-images.githubusercontent.com/26387222/78422095-12f05d80-765d-11ea-9387-3da6bf14d96a.png)

**Comment by RaphaelPage0110** [comment]
If I understand this card correctly, it would be nice to have a count of the tokens on the card?

**Comment by orichalque** [comment]
f7f7233
it'll be in the next release, with frosthaven support
