### ISSUE TITLE
Add support to Frosthaven Germinate faction

### ISSUE THREAD

**Issue by RaphaelPage0110** [orichalque/yet-an-other-gloomhaven-companion#64]
![image](https://user-images.githubusercontent.com/26387222/78422342-dde50a80-765e-11ea-8cd7-f6a5bf6037a8.png)

**Comment by RaphaelPage0110** [comment]
It would be nice for the player to select which state he is in.

**Comment by orichalque** [comment]
f7f7233
It'll be in the next release, with frosthaven
