### ISSUE TITLE
Remove special modifiers from the draw pile when drawn

### ISSUE THREAD

**Issue by RaphaelPage0110** [orichalque/yet-an-other-gloomhaven-companion#65]

**Comment by RaphaelPage0110** [comment]
I know that you should remove those two kind of cards from your deck after they are drawn :
![image](https://user-images.githubusercontent.com/26387222/78468994-059aa800-771d-11ea-86f1-34ae6f9ceacc.png) 
![image](https://user-images.githubusercontent.com/26387222/78469002-10edd380-771d-11ea-8088-04f67b5ff374.png)
But what about these ones?
![image](https://user-images.githubusercontent.com/26387222/78469008-282cc100-771d-11ea-906c-4b6ff1cdf951.png)
I can't find anything online @orichalque

**Comment by orichalque** [comment]
I checked the rules, blessings and curse should be destroyed on draw
the -1 added by the scenario should be removed at the end of the scenario :)

**Comment by RaphaelPage0110** [comment]
Closed with commit 58e120a5b19abae89d950d7d54b311c79fc68758
