### ISSUE TITLE
Show perks in modifiers selection

### ISSUE THREAD

**Issue by RaphaelPage0110** [orichalque/yet-an-other-gloomhaven-companion#70]

**Comment by orichalque** [comment]
Works fine for Vanilla. We dont have JoTL and Frosthaven perks though :p

**Comment by RaphaelPage0110** [comment]
Are you sure? I think we do!

**Comment by orichalque** [comment]
Oh, indeed. I have no idea why I couldnt see them. We can close this issue then ! ;)
