### ISSUE TITLE
Sawbones:  Too many +2 rolling modifiers

### ISSUE THREAD

**Issue by SawboneBuddy** [orichalque/yet-an-other-gloomhaven-companion#82]
The sawbones combat modifier selection shows (4) +2 rolling modifiers.  According to the perks sheet it should be (2) +2 and (2) +2 rolling modifiers.

![sawbones combat modifier deck](https://user-images.githubusercontent.com/63917423/79641657-e2cdb200-8166-11ea-9cb7-58d5b5980489.JPG)

![sawbones sheet](https://user-images.githubusercontent.com/63917423/79641661-ed884700-8166-11ea-8e22-c4b20a5588be.JPG)

Also, I love the app.  Thank you so much for doing this!

**Comment by orichalque** [comment]
Hi, thanks a lot for the issue, this is fixed !
