### ISSUE TITLE
Draggable play cards

### ISSUE THREAD

**Issue by RaphaelPage0110** [orichalque/yet-an-other-gloomhaven-companion#93]
It would be nice to be able to reorganize the ability cards in the play view. Maybe drag and drop?

**Comment by orichalque** [comment]
seems hella annoying to implement. lemme think about that ;-)

**Comment by brettmcginnis** [comment]
Created a pr for this https://github.com/orichalque/yet-an-other-gloomhaven-companion/pull/130
